server:
  port: 8080


# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'
    # SC 渠道配置 - 拼团对接渠道值、回调通知
    group-buy-market:
      api-url: http://127.0.0.1:8091/
      notify-url: http://127.0.0.1:8080/api/v1/alipay/group_buy_notify
      source: s01
      chanel: c01


# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/s-pay-mall-ddd-market?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: Retail_HikariCP
    minimum-idle: 15 #最小空闲连接数量
    idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
    maximum-pool-size: 25 #连接池最大连接数，默认是10
    auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
    max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
    connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
    connection-test-query: SELECT 1
  type: com.zaxxer.hikari.HikariDataSource

# RocketMQ 配置
rocketmq:
  name-server: 127.0.0.1:9876
  #  consumer:
  #    group: group_buy_team_success_consumer
  #    # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
  #    pull-batch-size: 10
  #    # topic
  #    topic: group_team_success_topic
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一
    group: group_buy_team_success_producer
    # 发送消息超时时间，默认3000
    sendMessageTimeout: 10000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    # 异步消息重试次数，默认2
    retryTimesWhenSendAsyncFailed: 2
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    maxMessageSize: 4096
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false
    # 刷盘策略，默认ASYNC(异步刷盘)
    enableMsgTrace: false

mq:
  producer:
    topic:
      team-success: group_team_success_topic



# Redis
redis:
  sdk:
    config:
      host: localhost
      port: 6379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true


# 微信公众号对接
weixin:
  config:
    originalid: gh_46ed3bee98b8
    token: b8b6
    app-id: wx93e7039a100120c8
    app-secret: 2ce18079942e191ee5fdb11c41656b8e
    template_id: RbEZ2jo47dQmF4A7_Ku7RsDy1x_5by6bk1Ox6rPCl4Y

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 2021000148678510
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCl0rRXf9PaEPRG/nmWJNQEkQWooPiaTwj9iuJ7r/usnqIAeLq2LppSX/BOlMpbexX5Hgxu2O6+i31FaTFc7+UfwxVYFyYQd+fiz64XNMKLVHJUigakTl0wQ7Bc2i9oj+whwY0gkCTl7+qFGzAVZV8vSlFoW54wNpHJms/z+/NgKdaw16Zml4yKNWAal5A/a+o3iNCiaQmh8Fbh4lZccZeTS3L85z6AD4biOLhaATFO9KfQlaXFa9lc+kpI8yAI91d9nnWiTIPVom9wpj/zOzaRZlow86HFv6xbQcfkyWATy9YQ+3k9wWFRryfrqJjzg4oleKoZO86TCuy530tzYU57AgMBAAECggEAUM12wXhxhD5kuj+AgfBaPAtq5XvjCFZg/CN0L29WxQvbxz0NRn85BdDoKXKJlMBKucSxrEYbOFCCb5NN0Yq4bJzERtOo4bd8EGLA41/7OKeiup0zlVb2Q/GH/Ab5uQsAtoY5PdffkwgwkEHqUVK/aizdtGuIjtfYfJPqp2prcrzHquvfSPt9m5cCZMM8wQcRQwBLebUiOV45KqvAH7yTn7hXIZH4yPRyr/gwvoYKMi3/NvP//dOCsGczAgI+MjokUY1r9pRZNLK46KuDqls/NPab0m435fYASc9RYLCkuc5EKdnQ0kY5D8Vx3yxoa3zknfjBfnpU3zzG4KryHp5xCQKBgQDPN9y0I734ks9X9kn5GpMe+cEGBMZjQC156i93kqHgV4SfH5zw99dE++XZnAgITleCSom10ry9v4Q9O4PJ8lLcMvchmuZsozzKqU0N1oaamZPWCuEkf02MkNa7R6+/nOmB0rFegk3+fKea0g3xYD5q2EvDjjMlRIvg/DKRr0GHhQKBgQDM3CMpkQ7+Z+0bNuE43s1P8TyLeLMPT53jROuUP7/VJdxFuGwrNwl4IGL6ItHh88tVTyAXNo/XGcEm+biKEf2HthcF4tuqytPGRo4wTzubYZUnPVv0uXCv8OZEHD8HB3U0Ix1LyHwfAaThsN5/6Vq3oMIYi/ss11xwSyncjWBd/wKBgQCMK9GT2YmsGENB0UyAwUU78t5rX9eDU+pvSccKL5po00rXCN908XIhK/Rzm2SjmbsAW8ODxyX9hQvDD/s6JD2Azsj1Zn7whgudW6DP94neEn06kOlzctnWeDOJRBjSmSYrt4Zb0/FGcLQ/uk/MM7qFNAMsKYjXcOLeMjtS6SZ+sQKBgFzk/fTdWGU4jyYmDp8RORylEYVVKC0rNzdVi1XgSobG8kmTRUmbXWnhlcBDhdTmDjAS/0RHc5ZgkVuxJWNGoSanBW2f32hlLP7eA6AYbbkZ2N7ATjB83oKJxIDiJhpz4UvRGHnC4bXVswS8hUiPcpmOBjXHVBCTX9Fz4/mlCivVAoGAQ1vrT/9sLnsnzVwQKFInFW0DT+UGGM3EK1bSHatHhVTgczxALvn0Zbr7ASus9jfzuXPgjYaLZJ6tXXEj5Pc7rGnqv3n7i9pe/38zGLY1P9Zy/qHA1iGDqx0NIgG1/iKD5ZuJol/7bwmFd89M12KGAVdQoO2403X3hPdnR3WCR9c=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr+2jEtMIGD86UtzGZOjGpk2SsuxrANCAd1MWNZyqdxBv3meK3SXKXqSAg8pCRkesRLJdRytoxDOXItz2g5P2qTWJSw+YKoCLeVAz7lMpPdWdjEZe4SN/+jueJhBKl2rQTLsNJcfvQo5HC/ox/qw7UB0DfHaW0tB+y9SinDOr9nxKuSffnp6Y8irvCyyT87gT1FP+b2rMsIlADjJfbtNn22gnnoi3cf5KLedsmLtGTOp0psc3NmfyhrByn9HIhp719Lyur2qBhg+9zXOolRoZ2DZmtLdbPRQeUH7/p4gbFgxmINpaf3wM0KTXmJWKWAui0W/2VYsfxhsk7h1IjjicYwIDAQAB
  notify_url: http://moying.natapp1.cc/api/v1/alipay/alipay_notify_url
  return_url: https://moying688.github.io/
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do


# MyBatis 配置【如需使用记得打开】
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml